# Generated by Django 6.0.5 on 2026-05-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
